# Generated by Django 4.1.7 on 2023-04-03 02:43

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [VectorExtension()]
