# Generated by Django 4.1.7 on 2023-04-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resume", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="HNJobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posted_by", models.CharField(max_length=200)),
                ("hn_id", models.IntegerField()),
                ("text", models.TextField()),
                ("time_posted", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
