# Generated by Django 4.1.7 on 2023-05-05 19:52

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resume", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="HNWhosHiringPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(unique=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("hash", models.PositiveBigIntegerField()),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HNJobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(unique=True)),
                ("posted_by", models.CharField(max_length=200)),
                ("time_posted", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
                ("raw_text", models.TextField()),
                ("display_text", models.TextField()),
                ("embedding_text", models.TextField()),
                (
                    "whos_hiring_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resume.hnwhoshiringpost",
                    ),
                ),
            ],
        ),
    ]
