# Generated by Django 4.1.7 on 2023-04-03 07:25

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hnjobposting",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
