# Generated by Django 4.1.7 on 2023-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0003_hnjobposting_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="HNWhosHiringPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hn_id", models.IntegerField(unique=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="hnjobposting",
            name="hn_id",
            field=models.IntegerField(unique=True),
        ),
    ]
