# Generated by Django 4.1.7 on 2023-04-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_hnwhoshiringpost_alter_hnjobposting_hn_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hnjobposting",
            name="whos_hiring_post",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="resume.hnwhoshiringpost",
            ),
            preserve_default=False,
        ),
    ]
