# Generated by Django 4.1.7 on 2023-05-29 05:38

import uuid

from django.db import migrations


def populate_uuid(apps, schema_editor):
    Resume = apps.get_model("resume", "Resume")
    for resume in Resume.objects.all():
        resume.uuid = uuid.uuid4()
        resume.save(update_fields=["uuid"])

class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_resume_uuid"),
    ]

    operations = [
        migrations.RunPython(populate_uuid, reverse_code=migrations.RunPython.noop),
    ]
