# Generated by Django 4.1.7 on 2023-04-04 06:04

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_hnjobposting_whos_hiring_post"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hnjobposting",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                lists=100,
                name="hnjobposting_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
