# Generated by Django 4.1.7 on 2023-05-29 05:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_auto_20230529_0538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
