# Generated by Django 4.1.7 on 2023-04-04 06:13

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_hnjobposting_hnjobposting_embedding_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hnjobposting",
            name="hnjobposting_embedding_idx",
        ),
        migrations.AddIndex(
            model_name="hnjobposting",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                lists=250,
                name="hnjobposting_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
