# Generated by Django 4.1.7 on 2023-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0007_remove_hnjobposting_hnjobposting_embedding_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hnjobposting",
            name="hnjobposting_embedding_idx",
        ),
    ]
