# Generated by Django 4.1.7 on 2023-04-06 05:44

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_remove_hnjobposting_hnjobposting_embedding_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hnjobposting",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
