# Generated by Django 4.1.7 on 2023-04-09 07:46

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_alter_hnjobposting_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("hash", models.PositiveIntegerField()),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
