# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0010_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="hash",
            field=models.PositiveBigIntegerField(),
        ),
    ]
