# Generated by Django 4.1.7 on 2023-04-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0011_alter_resume_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hnjobposting",
            old_name="text",
            new_name="embedding_text",
        ),
        migrations.AddField(
            model_name="hnjobposting",
            name="display_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hnjobposting",
            name="raw_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
